name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    env:
      DB_DATABASE: "meu_caderno"
      DB_USERNAME: "root"
      DB_HOST: "localhost"
      DB_PASSWORD: "Mrmario764*"
      DB_PORT: 3306
      DB_DIALECT: "mysql"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v4.0.4
    - run: npm install
    - run: /usr/local/lib/node_modules/pm2/bin/pm2 restart "my-book"

